-- RED COMERCIAL V5.0 - MASTER SQL SETUP SCRIPT
-- RUN THIS IN THE SUPABASE SQL EDITOR TO RESET AND CONFIGURE YOUR FULL DATABASE

-- ======================================================================================
-- 1. DROP EXISTING CONFLICTING VIEWS OR TABLES TO ENSURE CLEAN SLATE
-- ======================================================================================
DROP VIEW IF EXISTS public.produtos_estoque_baixo CASCADE;
DROP VIEW IF EXISTS public.clientes_inadimplentes CASCADE;
DROP VIEW IF EXISTS public.produtos CASCADE;

-- Drop all tables to restart (In correct dependency order to avoid foreign key failures)
DROP TABLE IF EXISTS public.admin_logs CASCADE;
DROP TABLE IF EXISTS public.admin_users CASCADE;
DROP TABLE IF EXISTS public.devolucoes CASCADE;
DROP TABLE IF EXISTS public.itens_venda CASCADE;
DROP TABLE IF EXISTS public.pagamentos_venda CASCADE;
DROP TABLE IF EXISTS public.vendas CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.tables CASCADE;
DROP TABLE IF EXISTS public.caixa_sessions CASCADE;
DROP TABLE IF EXISTS public.estoque_movimentacoes CASCADE;
DROP TABLE IF EXISTS public.stock_movements CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.cupons_desconto CASCADE;
DROP TABLE IF EXISTS public.leads CASCADE;
DROP TABLE IF EXISTS public.os CASCADE;
DROP TABLE IF EXISTS public.sales CASCADE;
DROP TABLE IF EXISTS public.vehicles CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.meta_vendas CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.user_preferences CASCADE;
DROP TABLE IF EXISTS public.tenant_users CASCADE;
DROP TABLE IF EXISTS public.system_logs CASCADE;
DROP TABLE IF EXISTS public.system_metrics CASCADE;
DROP TABLE IF EXISTS public.service_health CASCADE;
DROP TABLE IF EXISTS public.superadmin_settings CASCADE;
DROP TABLE IF EXISTS public.system_config CASCADE;
DROP TABLE IF EXISTS public.tenants CASCADE;

-- ======================================================================================
-- 2. MASTER / INDEPENDENT TABLES
-- ======================================================================================

CREATE TABLE public.tenants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  nome text NOT NULL,
  tipo text NOT NULL CHECK (tipo = ANY (ARRAY['restaurante'::text, 'concessionaria'::text, 'comercio'::text, 'farmacia'::text, 'clinica_consultorio'::text, 'salao_beleza'::text, 'academia'::text, 'hotel_hospedagem'::text, 'padaria_confeitaria'::text, 'ecommerce'::text, 'prestador_servicos'::text, 'supermercado'::text, 'distribuidora'::text])),
  descricao text,
  logo_url text,
  cnpj character varying UNIQUE,
  inscricao_estadual text,
  razao_social text,
  telefone character varying,
  email text,
  website text,
  endereco text,
  numero character varying,
  complemento text,
  bairro text,
  cidade text,
  estado character varying,
  cep character varying,
  latitude numeric,
  longitude numeric,
  ativo boolean DEFAULT true,
  plano text DEFAULT 'free'::text,
  max_usuarios integer DEFAULT 3,
  config jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pix_chave text,
  pix_tipo text DEFAULT 'cpf'::text,
  pix_titular text,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);

CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  username text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  senha_hash text NOT NULL,
  ativo boolean DEFAULT true,
  criado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  atualizado_em timestamp with time zone DEFAULT now(),
  senha text,
  CONSTRAINT admin_users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.superadmin_settings (
  key text NOT NULL,
  value text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT superadmin_settings_pkey PRIMARY KEY (key)
);

CREATE TABLE public.system_config (
  chave text NOT NULL,
  valor text,
  descricao text,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT system_config_pkey PRIMARY KEY (chave)
);

CREATE TABLE public.system_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  tenant_id uuid,
  level text,
  service text,
  message text,
  details jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE public.system_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  metrica text NOT NULL,
  valor numeric,
  detalhes jsonb,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT system_metrics_pkey PRIMARY KEY (id)
);

CREATE TABLE public.service_health (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  servico text NOT NULL,
  status text NOT NULL,
  latencia integer,
  detalhes jsonb,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT service_health_pkey PRIMARY KEY (id)
);

-- ======================================================================================
-- 3. TENANT DEPENDENT TABLES (LEVEL 1)
-- ======================================================================================

CREATE TABLE public.tenant_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  user_id uuid NOT NULL,
  papel text NOT NULL DEFAULT 'funcionario'::text,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  username text,
  ultima_atividade timestamp with time zone,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT tenant_users_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TABLE public.user_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tenant_id uuid,
  preferences jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_preferences_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  nome text NOT NULL,
  cpf_cnpj text,
  telefone text,
  email text,
  endereco text,
  cidade text,
  estado character varying,
  cep character varying,
  obs text,
  foto_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  nome text NOT NULL,
  descricao text,
  categoria text,
  preco numeric NOT NULL DEFAULT 0,
  preco_custo numeric,
  estoque_atual integer DEFAULT 0,
  estoque_minimo integer DEFAULT 0,
  unidade text DEFAULT 'un'::text,
  codigo_barras text,
  imagem_url text,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TABLE public.tables (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  numero integer NOT NULL,
  capacidade integer DEFAULT 4,
  status text DEFAULT 'livre'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tables_pkey PRIMARY KEY (id),
  CONSTRAINT tables_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TABLE public.caixa_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  aberto_por uuid,
  fechado_por uuid,
  aberto_at timestamp with time zone DEFAULT now(),
  fechado_at timestamp with time zone,
  fundo_troco numeric DEFAULT 0,
  total_vendas numeric DEFAULT 0,
  total_dinheiro numeric DEFAULT 0,
  total_pix numeric DEFAULT 0,
  total_cartao numeric DEFAULT 0,
  total_fiado numeric DEFAULT 0,
  total_outros numeric DEFAULT 0,
  obs_abertura text,
  obs_fechamento text,
  status text DEFAULT 'aberto'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT caixa_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT caixa_sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TABLE public.cupons_desconto (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  codigo text NOT NULL,
  descricao text,
  tipo text NOT NULL DEFAULT 'percentual'::text,
  valor numeric NOT NULL,
  valor_minimo numeric DEFAULT 0,
  ativo boolean DEFAULT true,
  data_inicio date,
  data_fim date,
  uso_maximo integer,
  usos_atuais integer DEFAULT 0,
  criado_em timestamp with time zone DEFAULT now(),
  criado_por uuid,
  CONSTRAINT cupons_desconto_pkey PRIMARY KEY (id),
  CONSTRAINT cupons_desconto_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TABLE public.meta_vendas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  mes integer NOT NULL,
  ano integer NOT NULL,
  meta numeric DEFAULT 0,
  CONSTRAINT meta_vendas_pkey PRIMARY KEY (id),
  CONSTRAINT meta_vendas_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  tipo text NOT NULL,
  categoria text,
  descricao text,
  valor numeric NOT NULL,
  data date NOT NULL DEFAULT CURRENT_DATE,
  pago boolean DEFAULT false,
  obs text,
  created_at timestamp with time zone DEFAULT now(),
  data_vencimento date DEFAULT CURRENT_DATE,
  data_pagamento date,
  valor_pago numeric,
  forma_pagamento text,
  beneficiario text,
  referencia_id uuid,
  referencia_tipo text,
  centro_custo text,
  recorrente boolean DEFAULT false,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

-- ======================================================================================
-- 4. TENANT DEPENDENT TABLES (LEVEL 2 - Dependent on Level 1 like Clients or Products)
-- ======================================================================================

CREATE TABLE public.vehicles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  client_id uuid,
  marca text,
  modelo text,
  versao text,
  ano_fab integer,
  ano_mod integer,
  cor text,
  placa text,
  chassi text,
  renavam text,
  km integer DEFAULT 0,
  combustivel text DEFAULT 'flex'::text,
  cambio text DEFAULT 'manual'::text,
  portas integer,
  preco numeric DEFAULT 0,
  preco_custo numeric,
  status text DEFAULT 'disponivel'::text,
  tipo text DEFAULT 'carro'::text,
  descricao text,
  fotos jsonb DEFAULT '[]'::jsonb,
  obs text,
  data_vencimento date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vehicles_pkey PRIMARY KEY (id),
  CONSTRAINT vehicles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT vehicles_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE
);

CREATE TABLE public.vendas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  client_id uuid,
  numero_venda bigint,
  subtotal numeric DEFAULT 0,
  total_desconto numeric DEFAULT 0, -- Fix for the code discrepancy
  total numeric DEFAULT 0,
  itens jsonb DEFAULT '[]'::jsonb, -- Missing column found in backend
  status text DEFAULT 'concluida'::text,
  notas text, -- Backend used notas instead of obs
  obs text,
  user_id uuid, -- Required by backend (who created sale)
  vendedor_id uuid,
  criado_em timestamp with time zone DEFAULT now(),
  atualizado_em timestamp with time zone DEFAULT now(),
  cancelado_em timestamp with time zone,
  CONSTRAINT vendas_pkey PRIMARY KEY (id),
  CONSTRAINT vendas_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT vendas_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE
);

-- Maintain compatibility with old code
CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  client_id uuid,
  vehicle_id uuid,
  valor numeric NOT NULL DEFAULT 0,
  forma_pagamento text,
  status text DEFAULT 'ativa'::text,
  data_vencimento date,
  obs text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sales_pkey PRIMARY KEY (id),
  CONSTRAINT sales_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT sales_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE,
  CONSTRAINT sales_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE
);

CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  table_id uuid,
  client_id uuid,
  numero_pedido integer NOT NULL,
  status text DEFAULT 'aberto'::text,
  total numeric DEFAULT 0,
  forma_pagamento text,
  is_delivery boolean DEFAULT false,
  delivery_nome text,
  delivery_pago boolean DEFAULT false,
  obs text,
  aberto_por uuid,
  fechado_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT orders_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.tables(id) ON DELETE CASCADE,
  CONSTRAINT orders_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE
);

CREATE TABLE public.admin_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  admin_id uuid,
  acao text NOT NULL,
  descricao text,
  dados jsonb,
  ip_address character varying,
  user_agent text,
  status_codigo integer,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT admin_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin_users(id) ON DELETE CASCADE
);

CREATE TABLE public.estoque_movimentacoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  product_id uuid,
  tipo text NOT NULL,
  quantidade integer NOT NULL,
  estoque_antes integer,
  estoque_depois integer,
  motivo text,
  custo_unit numeric,
  fornecedor text,
  nota_fiscal text,
  obs text,
  data date DEFAULT CURRENT_DATE,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT estoque_movimentacoes_pkey PRIMARY KEY (id),
  CONSTRAINT estoque_movimentacoes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT estoque_movimentacoes_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE
);

-- Old backend compat
CREATE TABLE public.stock_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  product_id uuid,
  tipo text NOT NULL,
  quantidade integer NOT NULL,
  estoque_antes integer,
  estoque_depois integer,
  motivo text,
  custo_unit numeric,
  fornecedor text,
  nota_fiscal text,
  obs text,
  data date DEFAULT CURRENT_DATE,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT stock_movements_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT stock_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE
);

-- ======================================================================================
-- 5. TENANT DEPENDENT TABLES (LEVEL 3 - Dependent on Sales/Orders/Vehicles)
-- ======================================================================================

CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  client_id uuid,
  vehicle_id uuid,
  status text DEFAULT 'novo'::text,
  origem text,
  valor_oferta numeric,
  obs text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT leads_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE,
  CONSTRAINT leads_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE
);

CREATE TABLE public.os (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  client_id uuid,
  vehicle_id uuid,
  descricao text NOT NULL,
  status text DEFAULT 'aberta'::text,
  pecas jsonb DEFAULT '[]'::jsonb,
  mao_obra numeric DEFAULT 0,
  total numeric DEFAULT 0,
  obs text,
  tecnico text,
  previsao date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT os_pkey PRIMARY KEY (id),
  CONSTRAINT os_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT os_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE,
  CONSTRAINT os_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE
);

CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  product_id uuid,
  nome text NOT NULL,
  qtd numeric NOT NULL DEFAULT 1,
  preco_unit numeric NOT NULL,
  subtotal numeric NOT NULL,
  obs text,
  destino text DEFAULT 'cozinha'::text,
  status_item text DEFAULT 'pendente'::text,
  codigo_barras text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE,
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE
);

CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  para_papel text,
  para_user_id uuid,
  tipo text NOT NULL,
  titulo text NOT NULL,
  mensagem text,
  order_id uuid,
  lida boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE,
  CONSTRAINT notifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE
);

CREATE TABLE public.itens_venda (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venda_id uuid NOT NULL,
  produto_id uuid,
  quantidade numeric NOT NULL DEFAULT 1,
  preco_unitario numeric NOT NULL,
  desconto_item numeric DEFAULT 0,
  subtotal numeric NOT NULL,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT itens_venda_pkey PRIMARY KEY (id),
  CONSTRAINT itens_venda_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id) ON DELETE CASCADE,
  CONSTRAINT itens_venda_produto_id_fkey FOREIGN KEY (produto_id) REFERENCES public.products(id) ON DELETE CASCADE
);

CREATE TABLE public.pagamentos_venda (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venda_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  forma text NOT NULL,
  valor numeric NOT NULL,
  status text DEFAULT 'confirmado'::text,
  referencia text,
  criado_em timestamp with time zone DEFAULT now(),
  CONSTRAINT pagamentos_venda_pkey PRIMARY KEY (id),
  CONSTRAINT pagamentos_venda_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id) ON DELETE CASCADE,
  CONSTRAINT pagamentos_venda_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

CREATE TABLE public.devolucoes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  venda_id uuid,
  tenant_id uuid NOT NULL,
  motivo text,
  itens jsonb DEFAULT '[]'::jsonb,
  valor_total numeric DEFAULT 0,
  reembolsado boolean DEFAULT false,
  data_reembolso timestamp with time zone,
  criado_em timestamp with time zone DEFAULT now(),
  processado_por uuid,
  CONSTRAINT devolucoes_pkey PRIMARY KEY (id),
  CONSTRAINT devolucoes_venda_id_fkey FOREIGN KEY (venda_id) REFERENCES public.vendas(id) ON DELETE CASCADE,
  CONSTRAINT devolucoes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE
);

-- ======================================================================================
-- 6. REQUIRED BACKEND VIEWS
-- ======================================================================================

-- Alias product -> produtos (Used in sales_v2.py)
CREATE VIEW public.produtos AS 
  SELECT * FROM public.products;

-- View for low stock items (produtos_estoque_baixo)
CREATE VIEW public.produtos_estoque_baixo AS 
  SELECT * FROM public.products
  WHERE estoque_atual <= estoque_minimo;

-- View for defaulting clients (clientes_inadimplentes) 
-- Joining clients with overdue transactions
CREATE VIEW public.clientes_inadimplentes AS
  SELECT DISTINCT c.* 
  FROM public.clients c
  INNER JOIN public.transactions t ON t.beneficiario = c.nome
  WHERE t.pago = false AND t.data_vencimento < CURRENT_DATE AND t.tipo = 'receita';


-- ======================================================================================
-- 7. ENABLE ROW LEVEL SECURITY (RLS) FOR ALL TENANT TABLES
-- ======================================================================================

-- First we enable it on all tables
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tenant_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caixa_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cupons_desconto ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meta_vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.estoque_movimentacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.os ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.itens_venda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagamentos_venda ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.devolucoes ENABLE ROW LEVEL SECURITY;

-- Creating a Function to extract the actual tenant_id from JWT token payload 
-- Supabase JWT injects app_metadata, assuming RED COMERCIAL python backend puts 'tenant_id' in there
CREATE OR REPLACE FUNCTION public.get_tenant_id() RETURNS uuid
    LANGUAGE sql STABLE
    AS $$
  select nullif(current_setting('request.jwt.claim.app_metadata', true)::json->>'tenant_id', '')::uuid;
$$;


-- Applying tenant isolation policies to everything except superadmin and public tables
-- (Assuming operations done by backend Service Role bypass these policies automatically)
CREATE POLICY "Tenants can only read own data" ON public.clients FOR ALL
  USING (tenant_id = public.get_tenant_id());
  
CREATE POLICY "Tenants can only read own products" ON public.products FOR ALL
  USING (tenant_id = public.get_tenant_id());

CREATE POLICY "Tenants can only read own sales" ON public.vendas FOR ALL
  USING (tenant_id = public.get_tenant_id());

CREATE POLICY "Tenants can only read own transactions" ON public.transactions FOR ALL
  USING (tenant_id = public.get_tenant_id());

CREATE POLICY "Tenant isolation for user details" ON public.tenant_users FOR ALL
  USING (tenant_id = public.get_tenant_id());

CREATE POLICY "Tenant isolation for generic sales" ON public.sales FOR ALL
  USING (tenant_id = public.get_tenant_id());

CREATE POLICY "Tenant isolation for orders" ON public.orders FOR ALL
  USING (tenant_id = public.get_tenant_id());

CREATE POLICY "Tenant isolation for restaurant tables" ON public.tables FOR ALL
  USING (tenant_id = public.get_tenant_id());

CREATE POLICY "Tenant permissions on themselves" ON public.tenants FOR SELECT
  USING (id = public.get_tenant_id());

-- End of Supabase Master Reset File
